---
:record_pattern: ".*.mp4"
:recordid_from_file_name: 
  :search: '(record_[\d]*)_[\d]*.mp4'
  :replace: 'RECORD_\1'
:get_record:
  :process: elasticsearch_get_record
  :params:
    :es_host: "https://host.docker.internal:9200"
    :es_index: "my_index"
:input_dirs:
  - '/records/input'
:output_dir: '/records/output'
:es_host: "http://elasticsearch:9200"
:es_index: "my_index"
:log_file: "/app/logs/example_logging.log"
:gconfig_path: "/app/config/"
:gconfig_application_credentials_file: "/app/config/application_default_credentials.json"
:gconfig_storage_bucket: icandid
  